name: nuclei
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.4.3
  - numpy=1.21.2
  - scikit-image=0.18.2
  - scikit-learn=0.24.2
  - scipy=1.7.1
  - tensorflow=2.4.1
  - streamlit=0.86.0
